#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Konoma.CrossFit.Resource", IsApplication=false)]

namespace Konoma.CrossFit
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public static int abc_vector_test = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x101011C,0x1010194,0x1010195,0x1010196,0x101030C,0x101030D }
			public static int[] AnimatedStateListDrawableCompat = new int[] {
					16843036,
					16843156,
					16843157,
					16843158,
					16843532,
					16843533};
			
			// aapt resource value: 3
			public static int AnimatedStateListDrawableCompat_android_constantSize = 3;
			
			// aapt resource value: 0
			public static int AnimatedStateListDrawableCompat_android_dither = 0;
			
			// aapt resource value: 4
			public static int AnimatedStateListDrawableCompat_android_enterFadeDuration = 4;
			
			// aapt resource value: 5
			public static int AnimatedStateListDrawableCompat_android_exitFadeDuration = 5;
			
			// aapt resource value: 2
			public static int AnimatedStateListDrawableCompat_android_variablePadding = 2;
			
			// aapt resource value: 1
			public static int AnimatedStateListDrawableCompat_android_visible = 1;
			
			// aapt resource value: { 0x10100D0,0x1010199 }
			public static int[] AnimatedStateListDrawableItem = new int[] {
					16842960,
					16843161};
			
			// aapt resource value: 1
			public static int AnimatedStateListDrawableItem_android_drawable = 1;
			
			// aapt resource value: 0
			public static int AnimatedStateListDrawableItem_android_id = 0;
			
			// aapt resource value: { 0x1010199,0x1010449,0x101044A,0x101044B }
			public static int[] AnimatedStateListDrawableTransition = new int[] {
					16843161,
					16843849,
					16843850,
					16843851};
			
			// aapt resource value: 0
			public static int AnimatedStateListDrawableTransition_android_drawable = 0;
			
			// aapt resource value: 2
			public static int AnimatedStateListDrawableTransition_android_fromId = 2;
			
			// aapt resource value: 3
			public static int AnimatedStateListDrawableTransition_android_reversible = 3;
			
			// aapt resource value: 1
			public static int AnimatedStateListDrawableTransition_android_toId = 1;
			
			// aapt resource value: { 0x101011C,0x1010194,0x1010195,0x1010196,0x101030C,0x101030D }
			public static int[] StateListDrawable = new int[] {
					16843036,
					16843156,
					16843157,
					16843158,
					16843532,
					16843533};
			
			// aapt resource value: { 0x1010199 }
			public static int[] StateListDrawableItem = new int[] {
					16843161};
			
			// aapt resource value: 0
			public static int StateListDrawableItem_android_drawable = 0;
			
			// aapt resource value: 3
			public static int StateListDrawable_android_constantSize = 3;
			
			// aapt resource value: 0
			public static int StateListDrawable_android_dither = 0;
			
			// aapt resource value: 4
			public static int StateListDrawable_android_enterFadeDuration = 4;
			
			// aapt resource value: 5
			public static int StateListDrawable_android_exitFadeDuration = 5;
			
			// aapt resource value: 2
			public static int StateListDrawable_android_variablePadding = 2;
			
			// aapt resource value: 1
			public static int StateListDrawable_android_visible = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
