name: Build Master

on:
  push:
    branches:
      - master

env:
  LIBRARY_NAME: Konoma.CrossFit
  NUGET_PASSWORD: ${{ secrets.KonomaPat }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Checkout Build Scripts
        uses: actions/checkout@v2
        with:
          repository: konoma/actions-buildscripts
          token: ${{ secrets.KonomaPat }}
          path: .build

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Build library
        run: |
          .build/xamarin-library/build.sh

      - name: Publish Library
        run: |
          .build/xamarin-library/publish.sh
