name: Build Pull Request

on: pull_request

env:
  LIBRARY_NAME: Konoma.CrossFit
  NUGET_PASSWORD: ${{ secrets.KonomaPat }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Checkout Build Scripts
        uses: actions/checkout@v3
        with:
          repository: konoma/actions-buildscripts
          branch: master
          token: ${{ secrets.KonomaPat }}
          path: .build

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Build library
        run: |
          .build/xamarin-library/build.sh
